name: Publish Docker Image
on:
  pull_request:
    types: [opend, synchronize, reopend]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      env:
        TZ: Asia/Tokyo
      run: |
        docker build \
          -t ${{ github.repository }}:${{ github.sha }} \
          -f ./docker/php/Dockerfile . \
          -build-arg TZ=${{ TZ }}
    - name: Login to registry
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
