name: Publish Image
on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'docker/**'
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  docker:
    name: build image and publish to registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      env:
        TZ: Asia/Tokyo
      run: |
        docker build \
          -t ${{ github.repository }}:${{ github.sha }} \
          -f ./docker/php/Dockerfile . \
          --build-arg TZ=$TZ
    - name: Login to registry
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        echo "$DOCKER_HUB_PASSWORD" | docker login \
          --username ${{ github.actor }} --password-stdin
    - name: Push image to registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        docker push ${{ github.repository }}:${{ github.sha }}
