name: Publish Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    types: [opend, synchronize, reopend]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: |
        docker build -t ${{ github.repository }}:${{ github.sha }} ./docker/php/Dockerfile
    - name: Login to registry
      run: |
        docker login -u ${{ github.actor }} -p ${{ secret.DOCKER_HUB_PASSWORD }}
